export const SET_USD_VALUES = "SET_USD_VALUES";
export const SET_WEB3_CLIENT = "SET_WEB3_CLIENT";

export const TOGGLE_NEW_BET_MODAL = "TOGGLE_NEW_BET_MODAL";
export const TOGGLE_CONNECTED = "TOGGLE_CONNECTED";